package:
  name: pyshapeit
  # This is the real version, used in releases:
  # version is the last TAG + the number of commits since
  # version: {{ environ.get('GIT_DESCRIBE_TAG', 'LOCAL').replace("_", ".").replace("Release.","") }}.{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  # This is the version used for the nightlies:
  # nightly version: 2020.09.1b.{{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}
  version: 2.0.0b.{{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}

source:
  git_url: https://github.com/rdkit/shape-it.git
  git_rev: main
  #path: ../..

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - cmake <=3.16
  host:
    - python
    - rdkit
  run:
    - python
    - rdkit
test:
  imports:
    - pyshapeit

about:
  license: MIT
